job_description_analysis:
  description: "Analyze the job description and generate tailored job experience content"
  expected_output: "BAR Statements of 4–6 sentences with each statement not more than 50 words tailored for ATS optimization"

job_experience_review:
  description: "Review the generated experience and improve clarity, tone, and keyword alignment"
  expected_output: "Final version suitable for pasting into a resume"
  output_file: "output/optimized_experience.txt"
